services:
  - type: web
    name: chinese-catto-1
    env: node
    region: london
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_URL
        value: https://chinese-catto-1.onrender.com
      - key: SESSION_SECRET
        value: chinese-catto-secret-change-in-production
      - key: GITHUB_CLIENT_ID
        value: ""
      - key: GITHUB_CLIENT_SECRET
        value: ""
